name: 'Version Bot'
description: 'Provides you with all app versioning needs'
author: 'App Company.io'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  token:
    description: 'Github Token to allow the bot to comment on pull requests'
    required: false
    default: ${{ github.token }}
  do-release:
    description: 'test'
    required: false
    default: 'false'
