name: 'Version Bot'
description: 'Provides you with all app versioning needs'
author: 'App Company.io'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  token:
    description: 'Github Token to allow the bot to comment on pull requests'
    required: false
    default: ${{ github.token }}
  pullRequest:
    description: 'pull request number'
    required: false
    default: ${{ github.event.pull_request.number }}
  release:
    description: 'test'
    required: false
    default: 'false'
  labels:
    description: 'update labels of pull request'
    required: false
    default: 'false'
  preview:
    description: 'generate preview for changelog'
    required: false
    default: 'false'
  changelog:
    description: 'generate changelog'
    required: false
    default: 'false'